const EN = {
  email: 'Email',
  password: 'Password',
  'password-mismatch': 'Passwords do not match',
  name: 'Name',
  'confirm-password': 'Confirm Password',
  gretting: 'Hello',
  archive: 'Archive',
  active: 'Active',
  create: 'Create',
  'create-notif': 'Note created successfully',
  'create-note': 'Create Note',
  logout: 'Logout',
  'logout-message': 'Are you sure you want to logout',
  back: 'Back to Dashboard',
  title: 'Title',
  body: 'Body',
  delete: 'Delete',
  'delete-notif': 'Note deleted successfully',
  'delete-message': 'Are you sure you want to delete this note?',
  'login-to-snap': 'Login to Snap',
  'dont-have-account': "Don't have an account?",
  register: 'Register',
  'register-notif': 'Registered successfully, please login',
  'register-to-snap': 'Register to Snap',
  login: 'Login',
  'already-have-account': 'Already have an account?',
  cancel: 'Cancel',
  'pretty-empty': 'Pretty empty around here',
  'archived-empty': 'List of archived notes is empty',
  'active-empty': 'List of active notes is empty',
  'empty-page-message':
    'Uppss.. the page you are looking for does not exist, please go back to the dashboard page 🏡🐾',
  eg: 'e.g.',
}

const ID = {
  email: 'Surel',
  password: 'Kata Sandi',
  'password-mismatch': 'Kata sandi tidak cocok',
  name: 'Nama',
  'confirm-password': 'Konfirmasi Kata Sandi',
  gretting: 'Halo',
  archive: 'Arsip',
  active: 'Aktif',
  create: 'Buat',
  'create-notif': 'Catatan berhasil dibuat',
  'create-note': 'Buat Catatan',
  logout: 'Keluar',
  'logout-message': 'Apakah Anda yakin ingin keluar',
  back: 'Kembali ke Dashboard',
  title: 'Judul',
  body: 'Isi',
  delete: 'Hapus',
  'delete-notif': 'Catatan berhasil dihapus',
  'delete-message': 'Apakah Anda yakin ingin menghapus catatan ini?',
  'login-to-snap': 'Masuk ke Snap',
  'dont-have-account': 'Belum punya akun?',
  register: 'Daftar',
  'register-notif': 'Pendaftaran berhasil, silahkan login',
  'register-to-snap': 'Daftar ke Snap',
  login: 'Masuk',
  'already-have-account': 'Sudah punya akun?',
  cancel: 'Batalkan',
  'pretty-empty': 'Cukup kosong di sekitar sini',
  'archived-empty': 'Daftar catatan yang diarsipkan kosong',
  'active-empty': 'Daftar catatan aktif kosong',
  'empty-page-message':
    'Uppss.. halaman yang Anda cari tidak ada, silahkan kembali ke halaman dashboard 🏡🐾',
  eg: 'cth.',
}

export { EN, ID }
